#!/bin/bash

#cleanup rhel  7.0
rm -rf LISISO/RHEL70/*.rpm
rm -rf LISISO/RHEL71/*.rpm
rm -rf LISISO/RHEL72/*.rpm
rm -rf LISISO/RHEL73/*.rpm
rm -rf LISISO/RHEL73/update/*.rpm
rm -rf LISISO/RHEL73/update1/*.rpm
rm -rf LISISO/RHEL73/update2/*.rpm
rm -rf LISISO/RHEL73/update3/*.rpm
rm -rf LISISO/RHEL73/update4/*.rpm
rm -rf LISISO/RHEL73/update5/*.rpm
rm -rf LISISO/RHEL73/update6/*.rpm
rm -rf LISISO/RHEL73/update7/*.rpm
rm -rf LISISO/RHEL73/update8/*.rpm
rm -rf LISISO/RHEL74/*.rpm
rm -rf LISISO/RHEL74/update1/*.rpm
rm -rf LISISO/RHEL74/update2/*.rpm
rm -rf LISISO/RHEL74/update3/*.rpm
rm -rf LISISO/RHEL74/update4/*.rpm
rm -rf LISISO/RHEL74/update5/*.rpm

#cleanup rhel  7.0
rm -rf LISISO/CentOS70/*.rpm
rm -rf LISISO/CentOS71/*.rpm
rm -rf LISISO/CentOS72/*.rpm
rm -rf LISISO/CentOS73/*.rpm
rm -rf LISISO/CentOS73/update/*.rpm
rm -rf LISISO/CentOS73/update1/*.rpm
rm -rf LISISO/CentOS73/update2/*.rpm
rm -rf LISISO/CentOS73/update3/*.rpm
rm -rf LISISO/CentOS73/update4/*.rpm
rm -rf LISISO/CentOS73/update5/*.rpm
rm -rf LISISO/CentOS73/update6/*.rpm
rm -rf LISISO/CentOS73/update7/*.rpm
rm -rf LISISO/CentOS73/update8/*.rpm
rm -rf LISISO/CentOS74/*.rpm
rm -rf LISISO/CentOS74/update1/*.rpm
rm -rf LISISO/CentOS74/update2/*.rpm
rm -rf LISISO/CentOS74/update3/*.rpm
rm -rf LISISO/CentOS74/update4/*.rpm
rm -rf LISISO/CentOS74/update5/*.rpm

#cleanup oracle  7.0
rm -rf LISISO/Oracle70/*.rpm
rm -rf LISISO/Oracle71/*.rpm
rm -rf LISISO/Oracle72/*.rpm
rm -rf LISISO/Oracle73/*.rpm
rm -rf LISISO/Oracle73/update/*.rpm
rm -rf LISISO/Oracle73/update1/*.rpm
rm -rf LISISO/Oracle73/update2/*.rpm
rm -rf LISISO/Oracle73/update3/*.rpm
rm -rf LISISO/Oracle73/update4/*.rpm
rm -rf LISISO/Oracle73/update5/*.rpm
rm -rf LISISO/Oracle73/update6/*.rpm
rm -rf LISISO/Oracle73/update7/*.rpm
rm -rf LISISO/Oracle73/update8/*.rpm
rm -rf LISISO/Oracle74/*.rpm
rm -rf LISISO/Oracle74/update1/*.rpm
rm -rf LISISO/Oracle74/update2/*.rpm
rm -rf LISISO/Oracle74/update3/*.rpm
rm -rf LISISO/Oracle74/update4/*.rpm
rm -rf LISISO/Oracle74/update5/*.rpm
